// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd4id4bSjH7-hPs6qQ5os7oWwSoo9piy4',
    appId: '1:394719793662:web:d69ad1b9210c25d73ff0af',
    messagingSenderId: '394719793662',
    projectId: 'ruby-delivery-app',
    authDomain: 'ruby-delivery-app.firebaseapp.com',
    storageBucket: 'ruby-delivery-app.appspot.com',
    measurementId: 'G-Z823EKG484',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGLVUC3TPVF6lWbJlnNIHsows_cc9nwQA',
    appId: '1:394719793662:android:3bad6a049cb25a673ff0af',
    messagingSenderId: '394719793662',
    projectId: 'ruby-delivery-app',
    storageBucket: 'ruby-delivery-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJXrO-q1NvCEYVPsuz3D4MttQy2GdE9_s',
    appId: '1:394719793662:ios:7e505d1248197b8c3ff0af',
    messagingSenderId: '394719793662',
    projectId: 'ruby-delivery-app',
    storageBucket: 'ruby-delivery-app.appspot.com',
    iosBundleId: 'com.example.kyogreDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd4id4bSjH7-hPs6qQ5os7oWwSoo9piy4',
    appId: '1:394719793662:web:3b0ffa923c2b6c123ff0af',
    messagingSenderId: '394719793662',
    projectId: 'ruby-delivery-app',
    authDomain: 'ruby-delivery-app.firebaseapp.com',
    storageBucket: 'ruby-delivery-app.appspot.com',
    measurementId: 'G-19XLE5DFNG',
  );
}
